# -*- coding: utf-8 -*-
"""analisis_territorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AQnWOCqJUWkHUKJg-HgLbDXsLa72uWoS
"""


import pandas as pd
import os

  
  
pres_gasto=pd.read_csv(r"bases_cuipo_contraloria/OVCF_-_CUIPO_-_Programaci_n_de_Gastos_20240213.csv")
pres_ingr=pd.read_csv(r"bases_cuipo_contraloria/OVCF_-_CUIPO_-_Programaci_n_de_Ingresos_20240213.csv")
eje_gasto=pd.read_csv(r"bases_cuipo_contraloria/OVCF_-_CUIPO_-_Ejecuci_n_de_Gastos_20240213.csv")
eje_ingr=pd.read_csv(r"bases_cuipo_contraloria/OVCF_-_CUIPO_-_Ejecuci_n_de_Ingresos_20240213.csv")

pres_gasto["tipo"]="pres_gasto"
pres_ingr["tipo"]="pres_ingreso"
eje_gasto["tipo"]="eje_gasto"
eje_ingr["tipo"]="eje_ingreso"


full=pd.concat([pres_gasto,pres_ingr], ignore_index=True)
full=pd.concat([full,eje_ingr], ignore_index=True)
full=pd.concat([full,eje_gasto], ignore_index=True)

pres_gasto=0
pres_ingr=0
eje_gasto=0
eje_ingr=0

names=full[['CODIGO_ENTIDAD',"NOMBRE_ENTIDAD"]].drop_duplicates(subset=['CODIGO_ENTIDAD'])
names.to_csv(r"dic/codigos_nombres")

for codigo in names["CODIGO_ENTIDAD"]:
    print(codigo)
    full[full["CODIGO_ENTIDAD"]==codigo].to_csv(
        r"bases_cuipo_contraloria/municipalities/"+str(codigo)+".csv")

